language: cpp

compiler:
 - clang
 - gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y cmake
  - sudo apt-get install -y libsdl2-dev

before_script:
  - mkdir build 
  - cd build
  - cmake ..

script:
  - make
