language: cpp

compiler:
 - clang
 - gcc

before_install:
  - sudo apt-get update
  - wget --no-check-certificate https://cmake.org/files/v3.5/cmake-3.5.0-rc2-Linux-i386.tar.gz
  - tar -xzf cmake-3.5.0-rc2-Linux-i386.tar.gz
  - sudo cp -fR cmake-3.5.0-rc2-Linux-i386/* /usr

before_script:
  - mkdir build 
  - cd build
  - cmake ..

script:
  - make
