language: cpp

compiler:
 - clang
 - gcc

before_install:
  - sudo apt-add-repository -y ppa:zoogie/sdl2-snapshots
  - sudo apt-get -qq update
  - sudo apt-get install -y cmake libsdl2-image-dev
  - cd external
  - git clone https://github.com/boostorg/boost
  - git clone https://github.com/erwincoumans/sce_vectormath
  - git clone https://github.com/bulletphysics/bullet3
  - git clone https://github.com/google/googletest
  - git clone https://github.com/Microsoft/GSL
  - cd GSL
  - cd tests
  - git clone https://github.com/Microsoft/unittest-cpp.git unittest-cpp
  - cd ..
  - cd ..
  - cd ..

before_script:
  - mkdir build 
  - cd build
  - cmake ..

script:
  - make
